### ISSUE TITLE
Pitch increases when Faster Song modifier is enabled

### ISSUE THREAD

**Issue by yoeyyutch** [sboys3/MusicSpatializer#2]
I'm using Oculus Rift CV1 and game version 1.6.1. 
Let me know if you want any more info. Thanks.

**Comment by sboys3** [comment]
I knew about that. Personally I prefer the pitch change over the artificial sounding speed only change. It might be possible for me to make it an option in the settings menu. Do you prefer it the regular way?

**Comment by yoeyyutch** [comment]
I just wanted to report it in case it was unintended.  I think you should leave it the way it is since that's what you like and the way you intended it to be. That would be my preference. Thank you for asking. 

Would you like me to close this issue? I see that I have the option to "Close and comment" Or if you want to keep it open, it's all good to me.

**Comment by queengooborg** [comment]
Personally, I feel that the pitch increase changes the overall mood of the songs in unintended ways, and I was a bit disappointed when I first heard it.   As a result, I temporarily disable the mod when playing a song with Faster Song enabled.  I would certainly love for this mod to retain Beat Saber's own speed adjustment behavior, both because I prefer it far more myself, and that's what players will expect!  Having a preference would be nice so that players have options (though I'm not sure how complex that would be).

**Comment by sboys3** [comment]
There is now an addon available that fixes this available. [`https://github.com/sboys3/MusicSpatializerPitchCorrection`](https://github.com/sboys3/MusicSpatializerPitchCorrection)

**Comment by MochyPei** [comment]
I know that's issue that last commented a long ago, but, i searching for some plugin for Beat Saber that can change default pitch correction for speed up, i'd too prefer to hear pithed up music when it speeded up 

> Personally I prefer the pitch change over the artificial sounding speed only change

I tried it on 1.29.1 version and it works how i wanted (i just turned off all effects in config file to not spatialize audio and get pitch up when turned speed up) but on 1.37 it's not work.
I really wanna just some small plugin with one switch in game, that turns pitch shift, because it sounds really better than cracked and bad quality but same pitch speeded up music. (I think i explained it properly, so, i wanna ask to make mod like this, because i don't have much knowledge about making plugins for beat saber)
